Resources:
  s3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-uni-buc-name-19876867723451116667
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: CFT
  ec2instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0fa3fe0fa7920f68e
      SecurityGroups:
        - default
      Tags:
        - Key: Name
          Value: MyEC2InstanceCFT